import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './context/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return ( // wrap session with provider so you can get userdata in following components
    <html lang="en">
      <Provider> 
       <body className={inter.className}>{children}</body>
      </Provider>  
    </html>
  )
}

